version: '3.8'

services:
  puppeteer-vinted-service:
    build: .
    container_name: puppeteer-vinted-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - default
      - n8n-network

networks:
  n8n-network:
    external: true
    name: pkkwkkkc04s04s84k8oo0k0o
